name: Upload to pypi

on:
  push:
    tags:
    - '*'

jobs:
  publish:
    name: build-and-publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: setup python37
        uses: actions/setup-python@v1
        with:
          python-version: 3.7
      - name: install poetry
        run: |
          curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py | python;
          echo "::add-path::$HOME/.poetry/bin/"
      - name: install deps
        run: poetry install -v
      - name: build package
        run: poetry build
      - name: Publish distribution 📦 to Test PyPI
        if: startsWith(github.ref, 'refs/tags/test-pypi-')
        uses: pypa/gh-action-pypi-publish@master
        with:
          password: ${{ secrets.TEST_PYPI_TOKEN }}
          repository_url: https://test.pypi.org/legacy/
      - name: Publish distribution 📦 to PyPI
        if: startsWith(github.ref, 'refs/tags/test-pypi-') == false
        uses: pypa/gh-action-pypi-publish@master
        with:
          password: ${{ secrets.PYPI_TOKEN }}
